docs_dir: _build/pydocmd
pages:
- Home: index.md
- layers:
  - Core layers: layers/core.md
  - Convolutional layers: layers/convolutional.md
  - normalization layers: layers/normalization.md
  - Advanced activations layers: layers/advanced-activations.md
  - CRF layers: layers/crf.md
- Losses: losses.md
- Optimizers: optimizers.md
- Callbacks: callbacks.md
site_dir: _build/site
site_name: Keras-contrib Documentation
theme: readthedocs
